// ============================================================================
//  TEMPLATE CATALOG
//  Each template is a structured letter. The app fills {{name}}, {{date}},
//  {{confirmation}} and a selectable {{signatory}} block.  Body text is the
//  fixed content extracted from the resort's Word vouchers.
//
//  Adding a NEW document type later (water-villa disclaimer, upgrade letter,
//  meal-plan upgrade, etc.) = add one object to this array. Nothing else
//  needs to change.
// ============================================================================

const SIGNATORIES = {
  silvia:  { name: "Silvia Sembenini", title: "Assistant Front Office Manager" },
  amelie:  { name: "Amelie Hacking",   title: "Front Office Manager" },
  tangi:   { name: "Tangi LeGrand",    title: "Regional General Manager" },
};

// A "body block" is an array of paragraphs. Lines beginning with "•" become
// bullet-style indented lines; lines wrapped in **...** render bold.
const TEMPLATES = [
  {
    id: "hm",
    category: "Honeymoon",
    label: "Honeymoon — Spa Discount",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination and we hope that you will enjoy your time with us.",
    lead: "We have great pleasure in informing you that you will be offered the benefit below during your stay:",
    body: [
      "**Honeymoon Offer — 50% discount on Special Honeymoon Spa Package**",
      "Once at Constance Spa",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact the Guest Relation team or Spa at extension 7199.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "hm_cup",
    category: "Honeymoon",
    label: "Honeymoon + Cristal Ultimate Package",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination and we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure of informing you that you will be offered the benefits below during your stay:",
    body: [
      "**Honeymoon Offer — 50% discount on Special Honeymoon Spa Package at Constance Spa**",
      "**Cristal Ultimate Package — Two different complimentary Experiences during your stay:**",
      "• “Traditional Sunset Fishing” (Scheduled on Monday and Friday)",
      "• “Sunset Snorkeling” (Scheduled on Wednesday and Saturday)",
      "• “Sunset Cruise” (Scheduled on Tuesday, Thursday and Sunday)",
      "_The excursion included in your Cristal Ultimate Package is not exchangeable or transferable to another excursion which is not mentioned above. The excursion can be rescheduled due to bad weather; however, it will not be refundable._",
    ],
    closing: "We truly hope that you enjoy these experiences and that they add to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact us at any time.",
    note: "Please be so kind to present this voucher to our team members when enjoying the above services.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "gwann",
    category: "Anniversary",
    label: "Wedding Anniversary — Spa Discount",
    intro: "Thank you for choosing Constance Halaveli Maldives for your holiday and we hope that you will enjoy your time with us.",
    lead: "We have great pleasure in informing you that you will be offered the benefit below during your stay:",
    body: [
      "**Wedding Anniversary Offer**",
      "50% discount on our Special Spa Package at Constance Spa",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can assist you with any further information, please contact the Guest Relation team or the Spa at extension 7199.",
    signoff: "Warm regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "gwann_cup",
    category: "Anniversary",
    label: "Anniversary + Cristal Ultimate Package",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination and we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure of informing you that you will be offered the benefits below during your stay:",
    body: [
      "**Anniversary Offer — 50% discount on Special Spa Package at Constance Spa**",
      "**Cristal Ultimate Package — Two different complimentary Experiences during your stay:**",
      "• “Traditional Sunset Fishing” (Scheduled on Monday and Friday)",
      "• “Sunset Snorkeling” (Scheduled on Wednesday and Saturday)",
      "• “Sunset Cruise” (Scheduled on Tuesday, Thursday and Sunday)",
      "_The excursion included in your Cristal Ultimate Package is not exchangeable or transferable to another excursion which is not mentioned above. The excursion can be rescheduled due to bad weather; however, it will not be refundable._",
    ],
    closing: "We sincerely hope that you will enjoy these benefits, and they will contribute to making your stay a memorable one.",
    contact: "If we can help you with any further information, please contact us at any time.",
    note: "Please be so kind to present this voucher to our team members when enjoying the above services.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "romantic_dinner",
    category: "Dining",
    label: "Romantic Dinner",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination and we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will be offered the below benefit during your stay:",
    body: [
      "**One Romantic Dinner set up at Jahaz Restaurant once during your stay**",
      "{{date}}",
    ],
    closing: "We truly hope that you enjoy these experiences and that they add to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact us at any time.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: true,
    dateLabel: "Booked on",
  },
  {
    id: "in_villa_breakfast",
    category: "Dining",
    label: "Floating Tray — In-Villa Breakfast (London)",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination. In addition, we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will be offered the below benefit during your stay:",
    body: [
      "**Added Value — One complimentary In-Villa London Floating Breakfast during your stay for 2 people**",
      "{{date}}",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact the Guest Relation team at 7140.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: true,
    dateLabel: "Scheduled on",
  },
  {
    id: "english_breakfast",
    category: "Dining",
    label: "Floating Tray — English Breakfast",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination. In addition, we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will be offered the below benefit during your stay:",
    body: [
      "**Added Value — One Complimentary Floating Tray English Breakfast during your stay for 2 people**",
      "{{date}}",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact the Guest Relation team at 7140.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: true,
    dateLabel: "Scheduled on",
  },
  {
    id: "london_breakfast",
    category: "Dining",
    label: "London Breakfast Floating Tray",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination. In addition, we hope that you will enjoy your time with us.",
    lead: "We have great pleasure in informing you that you will be offered the benefit below during your stay:",
    body: [
      "**Added Value: One Complimentary In-Villa Floating London Breakfast during your stay for 2 people**",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact the Guest Relation team at 7140.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "floating_lunch",
    category: "Dining",
    label: "Floating Tray — Lunch",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination. In addition, we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will be offered the below benefit during your stay:",
    body: [
      "**One complimentary Floating Tray Lunch during your stay**",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact the Guest Relation team at 7140.",
    signoff: "Warmest regards,",
    signatory: "amelie",
    hasDate: false,
  },
  {
    id: "in_villa_floating_tray",
    category: "Dining",
    label: "In-Villa Floating Tray Experience",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination. In addition, we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will be offered the below benefit during your stay:",
    body: [
      "**One complimentary In-Villa Floating Tray Experience during your stay**",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact the Guest Relation team at 7140.",
    signoff: "Warmest regards,",
    signatory: "amelie",
    hasDate: false,
  },
  {
    id: "bottle_wine",
    category: "Dining",
    label: "Complimentary Bottle of House Wine",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination and we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will be offered the below benefit during your stay:",
    body: [
      "**One Complimentary Bottle of House wine (red or white) once during stay**",
      "(Available at dinner)",
    ],
    closing: "We truly hope that you enjoy these experiences and that they add to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact us at any time.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "massage_30",
    category: "Spa",
    label: "Complimentary Massage — 30 Minutes",
    intro: "Welcome to Constance Halaveli Maldives! Thank you for choosing Constance Halaveli Maldives for your holidays and we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will enjoy the below benefit:",
    body: [
      "**Complimentary 30 minutes massage treatment (choice of Back, Neck, Shoulder, Scalp or Foot) per person during your stay.**",
      "(Treatment should be done between 11 am until 4 pm)",
    ],
    closing: "We truly hope that you enjoy this experience and that it adds to your pleasure and relaxation.",
    contact: "If we can help you with any further information, please contact us at any time.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "massage_60",
    category: "Spa",
    label: "Complimentary Massage — 60 Minutes",
    intro: "Thank you for choosing Constance Halaveli Maldives for your holidays and we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will enjoy the below benefit:",
    body: [
      "**Complimentary 60 minutes massage treatment per couple during your stay.**",
      "Please do not hesitate to contact our Spa or reception team to book your preferred treatment.",
    ],
    closing: "If we can assist you with any further information, please contact us at any time.",
    contact: "",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "cup",
    category: "Package",
    label: "Cristal Ultimate Package (CUP)",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination. In addition, we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure of informing you that you will be offered the benefits below during your stay:",
    body: [
      "**Cristal Ultimate Package — Two different complimentary Experiences during your stay:**",
      "• “Traditional Sunset Fishing” (Scheduled on Monday and Friday)",
      "• “Sunset Snorkeling” (Scheduled on Wednesday and Saturday)",
      "• “Sunset Cruise” (Scheduled on Tuesday, Thursday and Sunday)",
      "The complimentary excursions mentioned above are non-exchangeable with other activities outside of CUP. All excursions are to be booked at least 24 hours prior, and a minimum of 2 people is required.",
    ],
    closing: "We sincerely hope that you will enjoy these benefits, and they will contribute to making your stay a memorable one.",
    contact: "If we can help you with any further information, please contact us at any time.",
    signoff: "Warm regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "resort_credit_1000",
    category: "Resort Credit",
    label: "Resort Credit — USD 1000 per stay",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination and we hope that you will enjoy your time with us.",
    lead: "We have the great pleasure to inform you that you will enjoy the below benefit during your stay:",
    body: [
      "**Resort Credit of USD $1000 during your stay to be spent on food, drinks and SPA**",
    ],
    closing: "We sincerely hope that you will enjoy these benefits, and they will contribute to making your stay a memorable one.",
    contact: "If we can help you with any further information, please contact us at any time.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "resort_credit_daily",
    category: "Resort Credit",
    label: "Resort Credit — USD 100 per room per night",
    intro: "Thank you for choosing Constance Halaveli Maldives as your holiday destination and we hope that you will enjoy your time with us.",
    lead: "We have great pleasure in informing you that you will be offered the benefit below during your stay:",
    body: [
      "**Daily Resort credit of USD 100 per room per night to be spent on food, drinks and spa (Total USD 600)**",
      "(Applicable 01st May until 30th September 2026)",
    ],
    closing: "We sincerely hope that you will enjoy these benefits, and they will contribute to making your stay a memorable one.",
    contact: "If you require any additional information, please do not hesitate to contact our Reception or Guest Relations Team.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "gift_agent",
    category: "Gift",
    label: "Travel Agent Gift — Floating Tray Breakfast",
    intro: "Welcome to Constance Halaveli Maldives! We hope that you are enjoying your time with us here at Constance Halaveli.",
    lead: "We are pleased to offer you the gifts below from your travel agent:",
    body: [
      "**In-Villa Floating Tray Breakfast (“Remember” Menu) during your stay for 2 people**",
    ],
    closing: "We sincerely hope that you will enjoy these benefits, and they will contribute to make your stay a memorable one.",
    contact: "If you require any additional information, please do not hesitate to contact our Reception or Guest Relations team.",
    signoff: "Warmest regards,",
    signatory: "silvia",
    hasDate: false,
  },
  {
    id: "complimentary_stay",
    category: "Management",
    label: "Complimentary Stay Certificate (2 nights)",
    intro: "",
    lead: "This is to certify that we are pleased to extend a complimentary stay of two nights for your next visit to Constance Halaveli, on an All-Inclusive meal plan.",
    body: [
      "Please note that this voucher is valid for stays from {{date}} only.",
      "This voucher is issued as a gesture from the management team, and we look forward to welcoming you back for another memorable experience.",
    ],
    closing: "",
    contact: "",
    signoff: "Warmest regards,",
    signatory: "tangi",
    hasDate: true,
    dateLabel: "Valid",
    topDate: true,    // this letter shows a date at the very top
  },
];

module.exports = { TEMPLATES, SIGNATORIES };
